name: Update Cobrowse.io SDK and commit the changes

on: workflow_dispatch

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Find the latest SDK version and update build.gradle file
        run: |
          COBROWSE_VERSION=$(wget -O - -o /dev/null https://raw.githubusercontent.com/cobrowseio/cobrowse-sdk-android-binary/master/io/cobrowse/cobrowse-sdk-android/maven-metadata.xml | grep -Po '(?<=<version>)([0-9\.]+(-SNAPSHOT)?)' | sort --version-sort -r| head -n 1)
          sed -i "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" sample/build.gradle
          sed -i "s/\(io\.cobrowse\:cobrowse-sdk-android\:\).*/\\1${COBROWSE_VERSION}'/" standalone/build.gradle
      # If the SDK was updated, commit the changes
      - name: Commit the changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          FILES_TO_COMMIT: sample/build.gradle standalone/build.gradle
        run: |
          if [[ `git status --porcelain $FILES_TO_COMMIT` ]]; then
            # Commit as Github Actions Bot
            # https://github.com/actions/checkout?tab=readme-ov-file#push-a-commit-using-the-built-in-token
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add $FILES_TO_COMMIT
            git commit -m "feat: update Cobrowse.io SDK"
            git push
          else
            echo "No changes to commit"
          fi
